setting_name: CHESS_IR_SS_CG

team_agents:
  information_retriever:
    engine: 'deepseek-chat'
    tools:
      extract_keywords:
        template_name: 'extract_keywords'
        engine_config:
          engine_name: 'deepseek-chat'
          temperature: 0.2
        parser_name: 'python_list_output_parser'
      retrieve_entity: {}
      retrieve_context:
        top_k: 5
        
  candidate_generator:
    engine: 'deepseek-chat'
    tools:
      generate_candidate:
        generator_configs:
          - template_name: 'generate_candidate_one'
            engine_config:
              engine_name: 'deepseek-chat'
              temperature: 0.01
            parser_name: 'generate_candidate_gemini_markdown_cot'
            sampling_count: 1

      revise:
        template_name: 'revise_one'
        engine_config:
          engine_name: 'deepseek-chat'
          temperature: 0.0
        parser_name: 'revise_new'